name: 🧱 Build, Test & Report (Modern-package)

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pytest reportlab

      - name: Run tests
        run: pytest tests

      - name: Generate PDF report
        run: python scripts/generate_report.py

      - name: Upload report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: project-report
          path: docs/report.pdf
